### ISSUE TITLE
could not detect correctly

### ISSUE THREAD

**Issue by zzuzhp** [jeff-hykin/code-eol#11]
could not work if i mix use "LF" and "CRLF".
see the attachment. the 3rd line is ended with a single line feed character, while others
end with 'crlf'.
[test.txt](https://github.com/jeff-hykin/code-eol/files/3895311/test.txt)
(ultra edit works well)

**Comment by jeff-hykin** [comment]
Hi @zzuzhp, this is because VS Code itself does not support mixed line endings. There is an issue for it here: https://github.com/Microsoft/vscode/issues/127 It normalizes it when the file is opened, so there is nothing the extension can do.

Let me know if this wasn't exactly what you were meaning and I'll open this issue again.

**Comment by zzuzhp** [comment]
thanks, that is what i mean.
but, when i close the file, vscode doesn't normalize the endings, nothing happened. no window was poped. when file reopened, everything just remains the same.
(BTW: i created the file under windows and every line ends with crlf, then i reopen it with ultra edit ,switch to hex edit, and just delete '\0x0D' at the end of some line, leaving other lines untouched.)
i am using newest vscode on a MBP.
