### ISSUE TITLE
Is this extension can correctly render mixed line endings?

### ISSUE THREAD

**Issue by Mingun** [jeff-hykin/code-eol#12]
Today I got a merge conflict in my git working copy that was related to different line endings. It seems that part of lines ended with CR+LF and part with LF and the difference in some lines created a merge conflict. But when I tried this extension it showed me that all lines ended with the same sequence, which is configured in VSCode. I'm doubt that this was true, because then why git (GitKraken actually) shows me the difference?

So the question: did you rended _actual_ line endings or just the _configured_ one?

**Comment by jeff-hykin** [comment]
It renders whatever VS Code says the line ending is (line by line, not all at once). The source code is really simple if you want to take a look [here](https://github.com/jeff-hykin/code-eol/blob/a7ea2fe92237f1b19000dd0a45dd61227ffa64ce/index.js#L166). BUT, I think VS Code itself might be faking what the lines actually have.

In the bottom right of the editor it'll say LF or CRLF. I think whichever is auto-picked by VS Code, VS Code will then force for every line. 

I'd be interested; if you know you have a file with mixed line endings, and you open it with VS Code and then save it (without making any changes), could you see if that changed the line endings and made them all the same? If that's the case, there's not much the extension can do other than a ”read only" view where, instead of looking at the editor, it looks at the file path, then goes and reads the actual file instead.

**Comment by Mingun** [comment]
Yes, authors of other extensions said me that this is restriction of VS Code API itself. So practically all such extensions is useless -- for what reason I would need to see hypothetical newlines? That indicator is already present.

**Comment by jeff-hykin** [comment]
> for what reason I would need to see hypothetical newlines

To see trailing newlines, and simply see all whitespace in general. I prefer to see all whitespace.

And to be fair, part of wanting to see whitespace is to see individual line ending differences. I am annoyed that VS Code doesn't have an option to disable the auto-all-same.

That said, with enough effort it is probably possible to get around VS Code's behavior. Sadly I don't have time to work on elaborate workarounds though.
